#pragma once

/* mktmp name */
#define USTD_TMP_NAME(prefix)        _USTD_TMP_NAME1((prefix, __COUNTER__))
#define _USTD_TMP_NAME1(...)         _USTD_TMP_NAME2 __VA_ARGS__
#define _USTD_TMP_NAME2(prefix, id)  prefix##id

/* cast x to cstring */
#define USTD_STR(x)               USTD_STR1((x))
#define USTD_STR1(...)            USTD_STR2 __VA_ARGS__
#define USTD_STR2(...)            #__VA_ARGS__

/* return argument at index @id */
#define USTD_AT(id, ...)          USTD_AT_##id(__VA_ARGS__)

#define USTD_AT_0(_,...)          _
#define USTD_AT_1(_,...)          USTD_AT_0( __VA_ARGS__)
#define USTD_AT_2(_,...)          USTD_AT_1( __VA_ARGS__)
#define USTD_AT_3(_,...)          USTD_AT_2( __VA_ARGS__)
#define USTD_AT_4(_,...)          USTD_AT_3( __VA_ARGS__)
#define USTD_AT_5(_,...)          USTD_AT_4( __VA_ARGS__)
#define USTD_AT_6(_,...)          USTD_AT_5( __VA_ARGS__)
#define USTD_AT_7(_,...)          USTD_AT_6( __VA_ARGS__)
#define USTD_AT_8(_,...)          USTD_AT_7( __VA_ARGS__)
#define USTD_AT_9(_,...)          USTD_AT_8( __VA_ARGS__)
#define USTD_AT_10(_,...)         USTD_AT_9( __VA_ARGS__)
#define USTD_AT_11(_,...)         USTD_AT_10(__VA_ARGS__)
#define USTD_AT_12(_,...)         USTD_AT_11(__VA_ARGS__)
#define USTD_AT_13(_,...)         USTD_AT_12(__VA_ARGS__)
#define USTD_AT_14(_,...)         USTD_AT_13(__VA_ARGS__)
#define USTD_AT_15(_,...)         USTD_AT_14(__VA_ARGS__)
#define USTD_AT_16(_,...)         USTD_AT_15(__VA_ARGS__)
#define USTD_AT_17(_,...)         USTD_AT_16(__VA_ARGS__)
#define USTD_AT_18(_,...)         USTD_AT_17(__VA_ARGS__)
#define USTD_AT_19(_,...)         USTD_AT_18(__VA_ARGS__)
#define USTD_AT_20(_,...)         USTD_AT_19(__VA_ARGS__)
#define USTD_AT_21(_,...)         USTD_AT_20(__VA_ARGS__)
#define USTD_AT_22(_,...)         USTD_AT_21(__VA_ARGS__)
#define USTD_AT_23(_,...)         USTD_AT_22(__VA_ARGS__)
#define USTD_AT_24(_,...)         USTD_AT_23(__VA_ARGS__)
#define USTD_AT_25(_,...)         USTD_AT_24(__VA_ARGS__)
#define USTD_AT_26(_,...)         USTD_AT_25(__VA_ARGS__)
#define USTD_AT_27(_,...)         USTD_AT_26(__VA_ARGS__)
#define USTD_AT_28(_,...)         USTD_AT_27(__VA_ARGS__)
#define USTD_AT_29(_,...)         USTD_AT_28(__VA_ARGS__)
#define USTD_AT_30(_,...)         USTD_AT_29(__VA_ARGS__)
#define USTD_AT_31(_,...)         USTD_AT_30(__VA_ARGS__)
#define USTD_AT_32(_,...)         USTD_AT_31(__VA_ARGS__)
#define USTD_AT_33(_,...)         USTD_AT_32(__VA_ARGS__)
#define USTD_AT_34(_,...)         USTD_AT_33(__VA_ARGS__)
#define USTD_AT_35(_,...)         USTD_AT_34(__VA_ARGS__)
#define USTD_AT_36(_,...)         USTD_AT_35(__VA_ARGS__)
#define USTD_AT_37(_,...)         USTD_AT_36(__VA_ARGS__)
#define USTD_AT_38(_,...)         USTD_AT_37(__VA_ARGS__)
#define USTD_AT_39(_,...)         USTD_AT_38(__VA_ARGS__)
#define USTD_AT_40(_,...)         USTD_AT_39(__VA_ARGS__)
#define USTD_AT_41(_,...)         USTD_AT_40(__VA_ARGS__)
#define USTD_AT_42(_,...)         USTD_AT_41(__VA_ARGS__)
#define USTD_AT_43(_,...)         USTD_AT_42(__VA_ARGS__)
#define USTD_AT_44(_,...)         USTD_AT_43(__VA_ARGS__)
#define USTD_AT_45(_,...)         USTD_AT_44(__VA_ARGS__)
#define USTD_AT_46(_,...)         USTD_AT_45(__VA_ARGS__)
#define USTD_AT_47(_,...)         USTD_AT_46(__VA_ARGS__)
#define USTD_AT_48(_,...)         USTD_AT_47(__VA_ARGS__)
#define USTD_AT_49(_,...)         USTD_AT_48(__VA_ARGS__)
#define USTD_AT_50(_,...)         USTD_AT_49(__VA_ARGS__)
#define USTD_AT_51(_,...)         USTD_AT_50(__VA_ARGS__)
#define USTD_AT_52(_,...)         USTD_AT_51(__VA_ARGS__)
#define USTD_AT_53(_,...)         USTD_AT_52(__VA_ARGS__)
#define USTD_AT_54(_,...)         USTD_AT_53(__VA_ARGS__)
#define USTD_AT_55(_,...)         USTD_AT_54(__VA_ARGS__)
#define USTD_AT_56(_,...)         USTD_AT_55(__VA_ARGS__)
#define USTD_AT_57(_,...)         USTD_AT_56(__VA_ARGS__)
#define USTD_AT_58(_,...)         USTD_AT_57(__VA_ARGS__)
#define USTD_AT_59(_,...)         USTD_AT_58(__VA_ARGS__)
#define USTD_AT_60(_,...)         USTD_AT_59(__VA_ARGS__)
#define USTD_AT_61(_,...)         USTD_AT_60(__VA_ARGS__)
#define USTD_AT_62(_,...)         USTD_AT_61(__VA_ARGS__)
#define USTD_AT_63(_,...)         USTD_AT_62(__VA_ARGS__)
#define USTD_AT_64(_,...)         USTD_AT_63(__VA_ARGS__)
#define USTD_AT_65(_,...)         USTD_AT_64(__VA_ARGS__)
#define USTD_AT_66(_,...)         USTD_AT_65(__VA_ARGS__)
#define USTD_AT_67(_,...)         USTD_AT_66(__VA_ARGS__)
#define USTD_AT_68(_,...)         USTD_AT_67(__VA_ARGS__)
#define USTD_AT_69(_,...)         USTD_AT_68(__VA_ARGS__)
#define USTD_AT_70(_,...)         USTD_AT_69(__VA_ARGS__)
#define USTD_AT_71(_,...)         USTD_AT_70(__VA_ARGS__)
#define USTD_AT_72(_,...)         USTD_AT_71(__VA_ARGS__)
#define USTD_AT_73(_,...)         USTD_AT_72(__VA_ARGS__)
#define USTD_AT_74(_,...)         USTD_AT_73(__VA_ARGS__)
#define USTD_AT_75(_,...)         USTD_AT_74(__VA_ARGS__)
#define USTD_AT_76(_,...)         USTD_AT_75(__VA_ARGS__)
#define USTD_AT_77(_,...)         USTD_AT_76(__VA_ARGS__)
#define USTD_AT_78(_,...)         USTD_AT_77(__VA_ARGS__)
#define USTD_AT_79(_,...)         USTD_AT_78(__VA_ARGS__)
#define USTD_AT_80(_,...)         USTD_AT_79(__VA_ARGS__)
#define USTD_AT_81(_,...)         USTD_AT_80(__VA_ARGS__)
#define USTD_AT_82(_,...)         USTD_AT_81(__VA_ARGS__)
#define USTD_AT_83(_,...)         USTD_AT_82(__VA_ARGS__)
#define USTD_AT_84(_,...)         USTD_AT_83(__VA_ARGS__)
#define USTD_AT_85(_,...)         USTD_AT_84(__VA_ARGS__)
#define USTD_AT_86(_,...)         USTD_AT_85(__VA_ARGS__)
#define USTD_AT_87(_,...)         USTD_AT_86(__VA_ARGS__)
#define USTD_AT_88(_,...)         USTD_AT_87(__VA_ARGS__)
#define USTD_AT_89(_,...)         USTD_AT_88(__VA_ARGS__)
#define USTD_AT_90(_,...)         USTD_AT_89(__VA_ARGS__)
#define USTD_AT_91(_,...)         USTD_AT_90(__VA_ARGS__)
#define USTD_AT_92(_,...)         USTD_AT_91(__VA_ARGS__)
#define USTD_AT_93(_,...)         USTD_AT_92(__VA_ARGS__)
#define USTD_AT_94(_,...)         USTD_AT_93(__VA_ARGS__)
#define USTD_AT_95(_,...)         USTD_AT_94(__VA_ARGS__)
#define USTD_AT_96(_,...)         USTD_AT_95(__VA_ARGS__)
#define USTD_AT_97(_,...)         USTD_AT_96(__VA_ARGS__)
#define USTD_AT_98(_,...)         USTD_AT_97(__VA_ARGS__)
#define USTD_AT_99(_,...)         USTD_AT_98(__VA_ARGS__)

#define USTD_COUNT(...)           USTD_AT_99(##__VA_ARGS__, 99, 98, 97, 96, 95, 94, 93, 92, 91, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0)

#define USTD_FOR(f,...)           USTD_FOR_N((USTD_COUNT(__VA_ARGS__)), f, __VA_ARGS__)
#define USTD_FOR_N( n, ...)       USTD_FOR_ n(__VA_ARGS__)
#define USTD_FOR_(n)              USTD_FOR_##n

#define USTD_FOR_0( f,    ...)
#define USTD_FOR_1( f, t, ...)    f(t) USTD_FOR_0( f, __VA_ARGS__)
#define USTD_FOR_2( f, t, ...)    f(t) USTD_FOR_1( f, __VA_ARGS__)
#define USTD_FOR_3( f, t, ...)    f(t) USTD_FOR_2( f, __VA_ARGS__)
#define USTD_FOR_4( f, t, ...)    f(t) USTD_FOR_3( f, __VA_ARGS__)
#define USTD_FOR_5( f, t, ...)    f(t) USTD_FOR_4( f, __VA_ARGS__)
#define USTD_FOR_6( f, t, ...)    f(t) USTD_FOR_5( f, __VA_ARGS__)
#define USTD_FOR_7( f, t, ...)    f(t) USTD_FOR_6( f, __VA_ARGS__)
#define USTD_FOR_8( f, t, ...)    f(t) USTD_FOR_7( f, __VA_ARGS__)
#define USTD_FOR_9( f, t, ...)    f(t) USTD_FOR_8( f, __VA_ARGS__)
#define USTD_FOR_10(f, t, ...)    f(t) USTD_FOR_9( f, __VA_ARGS__)
#define USTD_FOR_11(f, t, ...)    f(t) USTD_FOR_10(f, __VA_ARGS__)
#define USTD_FOR_12(f, t, ...)    f(t) USTD_FOR_11(f, __VA_ARGS__)
#define USTD_FOR_13(f, t, ...)    f(t) USTD_FOR_12(f, __VA_ARGS__)
#define USTD_FOR_14(f, t, ...)    f(t) USTD_FOR_13(f, __VA_ARGS__)
#define USTD_FOR_15(f, t, ...)    f(t) USTD_FOR_14(f, __VA_ARGS__)
#define USTD_FOR_16(f, t, ...)    f(t) USTD_FOR_15(f, __VA_ARGS__)
#define USTD_FOR_17(f, t, ...)    f(t) USTD_FOR_16(f, __VA_ARGS__)
#define USTD_FOR_18(f, t, ...)    f(t) USTD_FOR_17(f, __VA_ARGS__)
#define USTD_FOR_19(f, t, ...)    f(t) USTD_FOR_18(f, __VA_ARGS__)
#define USTD_FOR_20(f, t, ...)    f(t) USTD_FOR_19(f, __VA_ARGS__)
#define USTD_FOR_21(f, t, ...)    f(t) USTD_FOR_20(f, __VA_ARGS__)
#define USTD_FOR_22(f, t, ...)    f(t) USTD_FOR_21(f, __VA_ARGS__)
#define USTD_FOR_23(f, t, ...)    f(t) USTD_FOR_22(f, __VA_ARGS__)
#define USTD_FOR_24(f, t, ...)    f(t) USTD_FOR_23(f, __VA_ARGS__)
#define USTD_FOR_25(f, t, ...)    f(t) USTD_FOR_24(f, __VA_ARGS__)
#define USTD_FOR_26(f, t, ...)    f(t) USTD_FOR_25(f, __VA_ARGS__)
#define USTD_FOR_27(f, t, ...)    f(t) USTD_FOR_26(f, __VA_ARGS__)
#define USTD_FOR_28(f, t, ...)    f(t) USTD_FOR_27(f, __VA_ARGS__)
#define USTD_FOR_29(f, t, ...)    f(t) USTD_FOR_28(f, __VA_ARGS__)
#define USTD_FOR_30(f, t, ...)    f(t) USTD_FOR_29(f, __VA_ARGS__)
#define USTD_FOR_31(f, t, ...)    f(t) USTD_FOR_30(f, __VA_ARGS__)
#define USTD_FOR_32(f, t, ...)    f(t) USTD_FOR_31(f, __VA_ARGS__)
#define USTD_FOR_33(f, t, ...)    f(t) USTD_FOR_32(f, __VA_ARGS__)
#define USTD_FOR_34(f, t, ...)    f(t) USTD_FOR_33(f, __VA_ARGS__)
#define USTD_FOR_35(f, t, ...)    f(t) USTD_FOR_34(f, __VA_ARGS__)
#define USTD_FOR_36(f, t, ...)    f(t) USTD_FOR_35(f, __VA_ARGS__)
#define USTD_FOR_37(f, t, ...)    f(t) USTD_FOR_36(f, __VA_ARGS__)
#define USTD_FOR_38(f, t, ...)    f(t) USTD_FOR_37(f, __VA_ARGS__)
#define USTD_FOR_39(f, t, ...)    f(t) USTD_FOR_38(f, __VA_ARGS__)
#define USTD_FOR_40(f, t, ...)    f(t) USTD_FOR_39(f, __VA_ARGS__)
#define USTD_FOR_41(f, t, ...)    f(t) USTD_FOR_40(f, __VA_ARGS__)
#define USTD_FOR_42(f, t, ...)    f(t) USTD_FOR_41(f, __VA_ARGS__)
#define USTD_FOR_43(f, t, ...)    f(t) USTD_FOR_42(f, __VA_ARGS__)
#define USTD_FOR_44(f, t, ...)    f(t) USTD_FOR_43(f, __VA_ARGS__)
#define USTD_FOR_45(f, t, ...)    f(t) USTD_FOR_44(f, __VA_ARGS__)
#define USTD_FOR_46(f, t, ...)    f(t) USTD_FOR_45(f, __VA_ARGS__)
#define USTD_FOR_47(f, t, ...)    f(t) USTD_FOR_46(f, __VA_ARGS__)
#define USTD_FOR_48(f, t, ...)    f(t) USTD_FOR_47(f, __VA_ARGS__)
#define USTD_FOR_49(f, t, ...)    f(t) USTD_FOR_48(f, __VA_ARGS__)
#define USTD_FOR_50(f, t, ...)    f(t) USTD_FOR_49(f, __VA_ARGS__)
#define USTD_FOR_51(f, t, ...)    f(t) USTD_FOR_50(f, __VA_ARGS__)
#define USTD_FOR_52(f, t, ...)    f(t) USTD_FOR_51(f, __VA_ARGS__)
#define USTD_FOR_53(f, t, ...)    f(t) USTD_FOR_52(f, __VA_ARGS__)
#define USTD_FOR_54(f, t, ...)    f(t) USTD_FOR_53(f, __VA_ARGS__)
#define USTD_FOR_55(f, t, ...)    f(t) USTD_FOR_54(f, __VA_ARGS__)
#define USTD_FOR_56(f, t, ...)    f(t) USTD_FOR_55(f, __VA_ARGS__)
#define USTD_FOR_57(f, t, ...)    f(t) USTD_FOR_56(f, __VA_ARGS__)
#define USTD_FOR_58(f, t, ...)    f(t) USTD_FOR_57(f, __VA_ARGS__)
#define USTD_FOR_59(f, t, ...)    f(t) USTD_FOR_58(f, __VA_ARGS__)
#define USTD_FOR_60(f, t, ...)    f(t) USTD_FOR_59(f, __VA_ARGS__)
#define USTD_FOR_61(f, t, ...)    f(t) USTD_FOR_60(f, __VA_ARGS__)
#define USTD_FOR_62(f, t, ...)    f(t) USTD_FOR_61(f, __VA_ARGS__)
#define USTD_FOR_63(f, t, ...)    f(t) USTD_FOR_62(f, __VA_ARGS__)
#define USTD_FOR_64(f, t, ...)    f(t) USTD_FOR_63(f, __VA_ARGS__)
#define USTD_FOR_65(f, t, ...)    f(t) USTD_FOR_64(f, __VA_ARGS__)
#define USTD_FOR_66(f, t, ...)    f(t) USTD_FOR_65(f, __VA_ARGS__)
#define USTD_FOR_67(f, t, ...)    f(t) USTD_FOR_66(f, __VA_ARGS__)
#define USTD_FOR_68(f, t, ...)    f(t) USTD_FOR_67(f, __VA_ARGS__)
#define USTD_FOR_69(f, t, ...)    f(t) USTD_FOR_68(f, __VA_ARGS__)
#define USTD_FOR_70(f, t, ...)    f(t) USTD_FOR_69(f, __VA_ARGS__)
#define USTD_FOR_71(f, t, ...)    f(t) USTD_FOR_70(f, __VA_ARGS__)
#define USTD_FOR_72(f, t, ...)    f(t) USTD_FOR_71(f, __VA_ARGS__)
#define USTD_FOR_73(f, t, ...)    f(t) USTD_FOR_72(f, __VA_ARGS__)
#define USTD_FOR_74(f, t, ...)    f(t) USTD_FOR_73(f, __VA_ARGS__)
#define USTD_FOR_75(f, t, ...)    f(t) USTD_FOR_74(f, __VA_ARGS__)
#define USTD_FOR_76(f, t, ...)    f(t) USTD_FOR_75(f, __VA_ARGS__)
#define USTD_FOR_77(f, t, ...)    f(t) USTD_FOR_76(f, __VA_ARGS__)
#define USTD_FOR_78(f, t, ...)    f(t) USTD_FOR_77(f, __VA_ARGS__)
#define USTD_FOR_79(f, t, ...)    f(t) USTD_FOR_78(f, __VA_ARGS__)
#define USTD_FOR_80(f, t, ...)    f(t) USTD_FOR_79(f, __VA_ARGS__)
#define USTD_FOR_81(f, t, ...)    f(t) USTD_FOR_80(f, __VA_ARGS__)
#define USTD_FOR_82(f, t, ...)    f(t) USTD_FOR_81(f, __VA_ARGS__)
#define USTD_FOR_83(f, t, ...)    f(t) USTD_FOR_82(f, __VA_ARGS__)
#define USTD_FOR_84(f, t, ...)    f(t) USTD_FOR_83(f, __VA_ARGS__)
#define USTD_FOR_85(f, t, ...)    f(t) USTD_FOR_84(f, __VA_ARGS__)
#define USTD_FOR_86(f, t, ...)    f(t) USTD_FOR_85(f, __VA_ARGS__)
#define USTD_FOR_87(f, t, ...)    f(t) USTD_FOR_86(f, __VA_ARGS__)
#define USTD_FOR_88(f, t, ...)    f(t) USTD_FOR_87(f, __VA_ARGS__)
#define USTD_FOR_89(f, t, ...)    f(t) USTD_FOR_88(f, __VA_ARGS__)
#define USTD_FOR_90(f, t, ...)    f(t) USTD_FOR_89(f, __VA_ARGS__)
#define USTD_FOR_91(f, t, ...)    f(t) USTD_FOR_90(f, __VA_ARGS__)
#define USTD_FOR_92(f, t, ...)    f(t) USTD_FOR_91(f, __VA_ARGS__)
#define USTD_FOR_93(f, t, ...)    f(t) USTD_FOR_92(f, __VA_ARGS__)
#define USTD_FOR_94(f, t, ...)    f(t) USTD_FOR_93(f, __VA_ARGS__)
#define USTD_FOR_95(f, t, ...)    f(t) USTD_FOR_94(f, __VA_ARGS__)
#define USTD_FOR_96(f, t, ...)    f(t) USTD_FOR_95(f, __VA_ARGS__)
#define USTD_FOR_97(f, t, ...)    f(t) USTD_FOR_96(f, __VA_ARGS__)
#define USTD_FOR_98(f, t, ...)    f(t) USTD_FOR_97(f, __VA_ARGS__)
#define USTD_FOR_99(f, t, ...)    f(t) USTD_FOR_98(f, __VA_ARGS__)

#define USTD_LOOP(n,f, ...)       USTD_LOOP_##n(f, __VA_ARGS__)
#define USTD_LOOP_0(f, ...)
#define USTD_LOOP_1(f, ...)       USTD_LOOP_0( f, __VA_ARGS__) f( 0, __VA_ARGS__)
#define USTD_LOOP_2(f, ...)       USTD_LOOP_1( f, __VA_ARGS__) f( 1, __VA_ARGS__)
#define USTD_LOOP_3(f, ...)       USTD_LOOP_2( f, __VA_ARGS__) f( 2, __VA_ARGS__)
#define USTD_LOOP_4(f, ...)       USTD_LOOP_3( f, __VA_ARGS__) f( 3, __VA_ARGS__)
#define USTD_LOOP_5(f, ...)       USTD_LOOP_4( f, __VA_ARGS__) f( 4, __VA_ARGS__)
#define USTD_LOOP_6(f, ...)       USTD_LOOP_5( f, __VA_ARGS__) f( 5, __VA_ARGS__)
#define USTD_LOOP_7(f, ...)       USTD_LOOP_6( f, __VA_ARGS__) f( 6, __VA_ARGS__)
#define USTD_LOOP_8(f, ...)       USTD_LOOP_7( f, __VA_ARGS__) f( 7, __VA_ARGS__)
#define USTD_LOOP_9(f, ...)       USTD_LOOP_8( f, __VA_ARGS__) f( 8, __VA_ARGS__)
#define USTD_LOOP_10(f, ...)      USTD_LOOP_9( f, __VA_ARGS__) f( 9, __VA_ARGS__)
#define USTD_LOOP_11(f, ...)      USTD_LOOP_10(f, __VA_ARGS__) f(10, __VA_ARGS__)
#define USTD_LOOP_12(f, ...)      USTD_LOOP_11(f, __VA_ARGS__) f(11, __VA_ARGS__)
#define USTD_LOOP_13(f, ...)      USTD_LOOP_12(f, __VA_ARGS__) f(12, __VA_ARGS__)
#define USTD_LOOP_14(f, ...)      USTD_LOOP_13(f, __VA_ARGS__) f(13, __VA_ARGS__)
#define USTD_LOOP_15(f, ...)      USTD_LOOP_14(f, __VA_ARGS__) f(14, __VA_ARGS__)
#define USTD_LOOP_16(f, ...)      USTD_LOOP_15(f, __VA_ARGS__) f(15, __VA_ARGS__)
#define USTD_LOOP_17(f, ...)      USTD_LOOP_16(f, __VA_ARGS__) f(16, __VA_ARGS__)
#define USTD_LOOP_18(f, ...)      USTD_LOOP_17(f, __VA_ARGS__) f(17, __VA_ARGS__)
#define USTD_LOOP_19(f, ...)      USTD_LOOP_18(f, __VA_ARGS__) f(18, __VA_ARGS__)
#define USTD_LOOP_20(f, ...)      USTD_LOOP_19(f, __VA_ARGS__) f(19, __VA_ARGS__)
#define USTD_LOOP_21(f, ...)      USTD_LOOP_20(f, __VA_ARGS__) f(20, __VA_ARGS__)
#define USTD_LOOP_22(f, ...)      USTD_LOOP_21(f, __VA_ARGS__) f(21, __VA_ARGS__)
#define USTD_LOOP_23(f, ...)      USTD_LOOP_22(f, __VA_ARGS__) f(22, __VA_ARGS__)
#define USTD_LOOP_24(f, ...)      USTD_LOOP_23(f, __VA_ARGS__) f(23, __VA_ARGS__)
#define USTD_LOOP_25(f, ...)      USTD_LOOP_24(f, __VA_ARGS__) f(24, __VA_ARGS__)
#define USTD_LOOP_26(f, ...)      USTD_LOOP_25(f, __VA_ARGS__) f(25, __VA_ARGS__)
#define USTD_LOOP_27(f, ...)      USTD_LOOP_26(f, __VA_ARGS__) f(26, __VA_ARGS__)
#define USTD_LOOP_28(f, ...)      USTD_LOOP_27(f, __VA_ARGS__) f(27, __VA_ARGS__)
#define USTD_LOOP_29(f, ...)      USTD_LOOP_28(f, __VA_ARGS__) f(28, __VA_ARGS__)
#define USTD_LOOP_30(f, ...)      USTD_LOOP_29(f, __VA_ARGS__) f(29, __VA_ARGS__)
#define USTD_LOOP_31(f, ...)      USTD_LOOP_30(f, __VA_ARGS__) f(30, __VA_ARGS__)
#define USTD_LOOP_32(f, ...)      USTD_LOOP_31(f, __VA_ARGS__) f(31, __VA_ARGS__)
#define USTD_LOOP_33(f, ...)      USTD_LOOP_32(f, __VA_ARGS__) f(32, __VA_ARGS__)
#define USTD_LOOP_34(f, ...)      USTD_LOOP_33(f, __VA_ARGS__) f(33, __VA_ARGS__)
#define USTD_LOOP_35(f, ...)      USTD_LOOP_34(f, __VA_ARGS__) f(34, __VA_ARGS__)
#define USTD_LOOP_36(f, ...)      USTD_LOOP_35(f, __VA_ARGS__) f(35, __VA_ARGS__)
#define USTD_LOOP_37(f, ...)      USTD_LOOP_36(f, __VA_ARGS__) f(36, __VA_ARGS__)
#define USTD_LOOP_38(f, ...)      USTD_LOOP_37(f, __VA_ARGS__) f(37, __VA_ARGS__)
#define USTD_LOOP_39(f, ...)      USTD_LOOP_38(f, __VA_ARGS__) f(38, __VA_ARGS__)
#define USTD_LOOP_40(f, ...)      USTD_LOOP_39(f, __VA_ARGS__) f(39, __VA_ARGS__)
#define USTD_LOOP_41(f, ...)      USTD_LOOP_40(f, __VA_ARGS__) f(40, __VA_ARGS__)
#define USTD_LOOP_42(f, ...)      USTD_LOOP_41(f, __VA_ARGS__) f(41, __VA_ARGS__)
#define USTD_LOOP_43(f, ...)      USTD_LOOP_42(f, __VA_ARGS__) f(42, __VA_ARGS__)
#define USTD_LOOP_44(f, ...)      USTD_LOOP_43(f, __VA_ARGS__) f(43, __VA_ARGS__)
#define USTD_LOOP_45(f, ...)      USTD_LOOP_44(f, __VA_ARGS__) f(44, __VA_ARGS__)
#define USTD_LOOP_46(f, ...)      USTD_LOOP_45(f, __VA_ARGS__) f(45, __VA_ARGS__)
#define USTD_LOOP_47(f, ...)      USTD_LOOP_46(f, __VA_ARGS__) f(46, __VA_ARGS__)
#define USTD_LOOP_48(f, ...)      USTD_LOOP_47(f, __VA_ARGS__) f(47, __VA_ARGS__)
#define USTD_LOOP_49(f, ...)      USTD_LOOP_48(f, __VA_ARGS__) f(48, __VA_ARGS__)
#define USTD_LOOP_50(f, ...)      USTD_LOOP_49(f, __VA_ARGS__) f(49, __VA_ARGS__)
#define USTD_LOOP_51(f, ...)      USTD_LOOP_50(f, __VA_ARGS__) f(50, __VA_ARGS__)
#define USTD_LOOP_52(f, ...)      USTD_LOOP_51(f, __VA_ARGS__) f(51, __VA_ARGS__)
#define USTD_LOOP_53(f, ...)      USTD_LOOP_52(f, __VA_ARGS__) f(52, __VA_ARGS__)
#define USTD_LOOP_54(f, ...)      USTD_LOOP_53(f, __VA_ARGS__) f(53, __VA_ARGS__)
#define USTD_LOOP_55(f, ...)      USTD_LOOP_54(f, __VA_ARGS__) f(54, __VA_ARGS__)
#define USTD_LOOP_56(f, ...)      USTD_LOOP_55(f, __VA_ARGS__) f(55, __VA_ARGS__)
#define USTD_LOOP_57(f, ...)      USTD_LOOP_56(f, __VA_ARGS__) f(56, __VA_ARGS__)
#define USTD_LOOP_58(f, ...)      USTD_LOOP_57(f, __VA_ARGS__) f(57, __VA_ARGS__)
#define USTD_LOOP_59(f, ...)      USTD_LOOP_58(f, __VA_ARGS__) f(58, __VA_ARGS__)
#define USTD_LOOP_60(f, ...)      USTD_LOOP_59(f, __VA_ARGS__) f(59, __VA_ARGS__)
#define USTD_LOOP_61(f, ...)      USTD_LOOP_60(f, __VA_ARGS__) f(60, __VA_ARGS__)
#define USTD_LOOP_62(f, ...)      USTD_LOOP_61(f, __VA_ARGS__) f(61, __VA_ARGS__)
#define USTD_LOOP_63(f, ...)      USTD_LOOP_62(f, __VA_ARGS__) f(62, __VA_ARGS__)
#define USTD_LOOP_64(f, ...)      USTD_LOOP_63(f, __VA_ARGS__) f(63, __VA_ARGS__)
#define USTD_LOOP_65(f, ...)      USTD_LOOP_64(f, __VA_ARGS__) f(64, __VA_ARGS__)
#define USTD_LOOP_66(f, ...)      USTD_LOOP_65(f, __VA_ARGS__) f(65, __VA_ARGS__)
#define USTD_LOOP_67(f, ...)      USTD_LOOP_66(f, __VA_ARGS__) f(66, __VA_ARGS__)
#define USTD_LOOP_68(f, ...)      USTD_LOOP_67(f, __VA_ARGS__) f(67, __VA_ARGS__)
#define USTD_LOOP_69(f, ...)      USTD_LOOP_68(f, __VA_ARGS__) f(68, __VA_ARGS__)
#define USTD_LOOP_70(f, ...)      USTD_LOOP_69(f, __VA_ARGS__) f(69, __VA_ARGS__)
#define USTD_LOOP_71(f, ...)      USTD_LOOP_70(f, __VA_ARGS__) f(70, __VA_ARGS__)
#define USTD_LOOP_72(f, ...)      USTD_LOOP_71(f, __VA_ARGS__) f(71, __VA_ARGS__)
#define USTD_LOOP_73(f, ...)      USTD_LOOP_72(f, __VA_ARGS__) f(72, __VA_ARGS__)
#define USTD_LOOP_74(f, ...)      USTD_LOOP_73(f, __VA_ARGS__) f(73, __VA_ARGS__)
#define USTD_LOOP_75(f, ...)      USTD_LOOP_74(f, __VA_ARGS__) f(74, __VA_ARGS__)
#define USTD_LOOP_76(f, ...)      USTD_LOOP_75(f, __VA_ARGS__) f(75, __VA_ARGS__)
#define USTD_LOOP_77(f, ...)      USTD_LOOP_76(f, __VA_ARGS__) f(76, __VA_ARGS__)
#define USTD_LOOP_78(f, ...)      USTD_LOOP_77(f, __VA_ARGS__) f(77, __VA_ARGS__)
#define USTD_LOOP_79(f, ...)      USTD_LOOP_78(f, __VA_ARGS__) f(78, __VA_ARGS__)
#define USTD_LOOP_80(f, ...)      USTD_LOOP_79(f, __VA_ARGS__) f(79, __VA_ARGS__)
#define USTD_LOOP_81(f, ...)      USTD_LOOP_80(f, __VA_ARGS__) f(80, __VA_ARGS__)
#define USTD_LOOP_82(f, ...)      USTD_LOOP_81(f, __VA_ARGS__) f(81, __VA_ARGS__)
#define USTD_LOOP_83(f, ...)      USTD_LOOP_82(f, __VA_ARGS__) f(82, __VA_ARGS__)
#define USTD_LOOP_84(f, ...)      USTD_LOOP_83(f, __VA_ARGS__) f(83, __VA_ARGS__)
#define USTD_LOOP_85(f, ...)      USTD_LOOP_84(f, __VA_ARGS__) f(84, __VA_ARGS__)
#define USTD_LOOP_86(f, ...)      USTD_LOOP_85(f, __VA_ARGS__) f(85, __VA_ARGS__)
#define USTD_LOOP_87(f, ...)      USTD_LOOP_86(f, __VA_ARGS__) f(86, __VA_ARGS__)
#define USTD_LOOP_88(f, ...)      USTD_LOOP_87(f, __VA_ARGS__) f(87, __VA_ARGS__)
#define USTD_LOOP_89(f, ...)      USTD_LOOP_88(f, __VA_ARGS__) f(88, __VA_ARGS__)
#define USTD_LOOP_90(f, ...)      USTD_LOOP_89(f, __VA_ARGS__) f(89, __VA_ARGS__)
#define USTD_LOOP_91(f, ...)      USTD_LOOP_90(f, __VA_ARGS__) f(90, __VA_ARGS__)
#define USTD_LOOP_92(f, ...)      USTD_LOOP_91(f, __VA_ARGS__) f(91, __VA_ARGS__)
#define USTD_LOOP_93(f, ...)      USTD_LOOP_92(f, __VA_ARGS__) f(92, __VA_ARGS__)
#define USTD_LOOP_94(f, ...)      USTD_LOOP_93(f, __VA_ARGS__) f(93, __VA_ARGS__)
#define USTD_LOOP_95(f, ...)      USTD_LOOP_94(f, __VA_ARGS__) f(94, __VA_ARGS__)
#define USTD_LOOP_96(f, ...)      USTD_LOOP_95(f, __VA_ARGS__) f(95, __VA_ARGS__)
#define USTD_LOOP_97(f, ...)      USTD_LOOP_96(f, __VA_ARGS__) f(96, __VA_ARGS__)
#define USTD_LOOP_98(f, ...)      USTD_LOOP_97(f, __VA_ARGS__) f(97, __VA_ARGS__)
#define USTD_LOOP_99(f, ...)      USTD_LOOP_98(f, __VA_ARGS__) f(98, __VA_ARGS__)
